# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(choices=[('', 'Seleccione una provincia'), ('Buenos Aires', 'Buenos Aires'), ('Catamarca', 'Catamarca'), ('Chaco', 'Chaco'), ('Chubut', 'Chubut'), ('Cordoba', 'Cordoba'), ('Corrientes', 'Corrientes'), ('Entre Rios', 'Entre Rios'), ('Formosa', 'Formosa'), ('Jujuy', 'Jujuy'), ('La Pampa', 'La Pampa'), ('La Rioja', 'La Rioja'), ('Mendoza', 'Mendoza'), ('Misiones', 'Misiones'), ('Neuquen', 'Neuquen'), ('Rio Negro', 'Rio Negro'), ('Salta', 'Salta'), ('San Juan', 'San Juan'), ('San Luis', 'San Luis'), ('Santa Cruz', 'Santa Cruz'), ('Santa Fe', 'Santa Fe'), ('Tierra del Fuego', 'Tierra del Fuego'), ('Tucuman', 'Tucuman')], default='', max_length=100)),
                ('localidad', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=100)),
                ('responsableInscripto', models.CharField(choices=[('', 'Seleccione una categor\xeda'), ('Responsable no inscripto', 'Responsable no inscripto'), ('Responsable inscripto - Categoria A', 'Responsable inscripto - Categor\xeda A'), ('Responsable inscripto - Categoria B', 'Responsable inscripto - Categor\xeda B'), ('Responsable inscripto - Categoria C', 'Responsable inscripto - Categor\xeda C'), ('Responsable inscripto - Categoria D', 'Responsable inscripto - Categor\xeda D'), ('Monotributista - Categoria A', 'Monotributista - Categor\xeda A'), ('Monotributista - Categoria B', 'Monotributista - Categor\xeda B'), ('Monotributista - Categoria C', 'Monotributista - Categor\xeda C'), ('Monotributista - Categoria D', 'Monotributista - Categor\xeda D'), ('Monotributista - Categoria E', 'Monotributista - Categor\xeda E'), ('Monotributista - Categoria F', 'Monotributista - Categor\xeda F')], default='', max_length=100)),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Direccion')),
            ],
        ),
    ]
